# Generated by Django 3.0 on 2021-05-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
